swagger: '2.0'
info:
  title: HTTP API Console sigmoid.sigmoid
  name: ''
  description: ''
paths:
  /sigmoid/sigmoid/get_amount/{senderAddress}:
    get:
      operationId: Query_GetAmount
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              amount:
                type: string
                format: uint64
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      parameters:
        - name: senderAddress
          in: path
          required: true
          type: string
      tags:
        - Query
  /sigmoid/sigmoid/get_last_processed:
    get:
      operationId: Query_GetLastProcessed
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              transactionId:
                type: string
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      tags:
        - Query
  /sigmoid/sigmoid/get_latest_processed_eth_block:
    get:
      operationId: Query_GetLatestProcessedEthBlock
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              blockNumber:
                type: string
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      tags:
        - Query
  /sigmoid/sigmoid/get_pending_bridge_request:
    get:
      operationId: Query_GetPendingBridgeRequest
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              request:
                type: object
                properties:
                  creator:
                    type: string
                  erc20Address:
                    type: string
                  amount:
                    type: string
                    format: uint64
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      tags:
        - Query
  /sigmoid/sigmoid/get_pending_unstake_request:
    get:
      operationId: Query_GetPendingUnstakeRequest
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              request:
                type: object
                properties:
                  creator:
                    type: string
                  unstakeAddress:
                    type: string
                  amount:
                    type: string
                    format: uint64
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      tags:
        - Query
  /sigmoid/sigmoid/get_rao_staked_balance:
    get:
      operationId: Query_GetRaoStakedBalance
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              raoStakedBalance:
                type: string
                format: uint64
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      tags:
        - Query
  /sigmoid/sigmoid/get_sigtao_rate_d:
    get:
      operationId: Query_GetSigtaoRateD
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              sigtaoRateD:
                type: string
                format: uint64
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      tags:
        - Query
  /sigmoid/sigmoid/params:
    get:
      operationId: Query_Params
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              params:
                type: object
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      tags:
        - Query
definitions:
  Any:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  Status:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          properties:
            '@type':
              type: string
          additionalProperties: {}
  MsgCreateBridgeRequest:
    type: object
    properties:
      creator:
        type: string
      erc20Address:
        type: string
      amount:
        type: string
        format: uint64
  MsgCreateUnstakeRequest:
    type: object
    properties:
      creator:
        type: string
      unstakeAddress:
        type: string
      amount:
        type: string
        format: uint64
  Params:
    type: object
  QueryGetAmountResponse:
    type: object
    properties:
      amount:
        type: string
        format: uint64
  QueryGetLastProcessedResponse:
    type: object
    properties:
      transactionId:
        type: string
  QueryGetLatestProcessedEthBlockResponse:
    type: object
    properties:
      blockNumber:
        type: string
  QueryGetPendingBridgeRequestResponse:
    type: object
    properties:
      request:
        type: object
        properties:
          creator:
            type: string
          erc20Address:
            type: string
          amount:
            type: string
            format: uint64
  QueryGetPendingUnstakeRequestResponse:
    type: object
    properties:
      request:
        type: object
        properties:
          creator:
            type: string
          unstakeAddress:
            type: string
          amount:
            type: string
            format: uint64
  QueryGetRaoStakedBalanceResponse:
    type: object
    properties:
      raoStakedBalance:
        type: string
        format: uint64
  QueryGetSigtaoRateDResponse:
    type: object
    properties:
      sigtaoRateD:
        type: string
        format: uint64
  QueryParamsResponse:
    type: object
    properties:
      params:
        type: object
  MsgApproveBridgeRequestResponse:
    type: object
  MsgApproveRequestResponse:
    type: object
  MsgApproveUnstakeRequestResponse:
    type: object
  MsgCreateBridgeRequestResponse:
    type: object
  MsgCreateRequestResponse:
    type: object
  MsgCreateRequestSignedResponse:
    type: object
  MsgCreateUnstakeRequestResponse:
    type: object
  MsgIncomeBridgeRequestResponse:
    type: object
  MsgProcessTransactionResponse:
    type: object
  MsgSetLatestProcessedEthBlockResponse:
    type: object
  MsgSetRaoCurrentStakedBalanceResponse:
    type: object
  MsgUpdateParamsResponse:
    type: object
