swagger: '2.0'
info:
  title: HTTP API Console sigmoidtest.sigmoidtest
  name: ''
  description: ''
paths:
  /sigmoid-test/sigmoidtest/get_amount/{senderAddress}:
    get:
      operationId: Query_GetAmount
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              amount:
                type: string
                format: uint64
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      parameters:
        - name: senderAddress
          in: path
          required: true
          type: string
      tags:
        - Query
  /sigmoid-test/sigmoidtest/get_front_stake_request/{creator}:
    get:
      operationId: Query_GetFrontStakeRequest
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              frontStakeRequest:
                type: array
                items:
                  type: object
                  properties:
                    sender:
                      type: string
                    mint:
                      type: string
                    status:
                      type: string
                      format: uint64
                    amount:
                      type: string
                      format: uint64
                    transactionId:
                      type: string
              pagination:
                type: object
                properties:
                  next_key:
                    type: string
                    format: byte
                  total:
                    type: string
                    format: uint64
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      parameters:
        - name: creator
          in: path
          required: true
          type: string
        - name: pagination.key
          in: query
          required: false
          type: string
          format: byte
        - name: pagination.offset
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.limit
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.count_total
          in: query
          required: false
          type: boolean
        - name: pagination.reverse
          in: query
          required: false
          type: boolean
      tags:
        - Query
  /sigmoid-test/sigmoidtest/get_last_processed:
    get:
      operationId: Query_GetLastProcessed
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              transactionId:
                type: string
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      tags:
        - Query
  /sigmoid-test/sigmoidtest/params:
    get:
      operationId: Query_Params
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              params:
                type: object
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      tags:
        - Query
definitions:
  Any:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  Status:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          properties:
            '@type':
              type: string
          additionalProperties: {}
  FrontStakeRequest:
    type: object
    properties:
      sender:
        type: string
      mint:
        type: string
      status:
        type: string
        format: uint64
      amount:
        type: string
        format: uint64
      transactionId:
        type: string
  PageRequest:
    type: object
    properties:
      key:
        type: string
        format: byte
      offset:
        type: string
        format: uint64
      limit:
        type: string
        format: uint64
      count_total:
        type: boolean
      reverse:
        type: boolean
  PageResponse:
    type: object
    properties:
      next_key:
        type: string
        format: byte
      total:
        type: string
        format: uint64
  Params:
    type: object
  QueryGetAmountResponse:
    type: object
    properties:
      amount:
        type: string
        format: uint64
  QueryGetFrontStakeRequestResponse:
    type: object
    properties:
      frontStakeRequest:
        type: array
        items:
          type: object
          properties:
            sender:
              type: string
            mint:
              type: string
            status:
              type: string
              format: uint64
            amount:
              type: string
              format: uint64
            transactionId:
              type: string
      pagination:
        type: object
        properties:
          next_key:
            type: string
            format: byte
          total:
            type: string
            format: uint64
  QueryGetLastProcessedResponse:
    type: object
    properties:
      transactionId:
        type: string
  QueryParamsResponse:
    type: object
    properties:
      params:
        type: object
  MsgApproveRequestResponse:
    type: object
  MsgCreateRequestResponse:
    type: object
  MsgProcessTransactionResponse:
    type: object
  MsgUpdateParamsResponse:
    type: object
