swagger: '2.0'
info:
  title: HTTP API Console sigmoidtest.sigmoidtest
  name: ''
  description: ''
paths:
  /sigmoid-test/sigmoidtest/get_amount/{senderAddress}:
    get:
      operationId: Query_GetAmount
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              amount:
                type: string
                format: uint64
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      parameters:
        - name: senderAddress
          in: path
          required: true
          type: string
      tags:
        - Query
  /sigmoid-test/sigmoidtest/get_last_processed:
    get:
      operationId: Query_GetLastProcessed
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              transactionId:
                type: string
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      tags:
        - Query
  /sigmoid-test/sigmoidtest/params:
    get:
      operationId: Query_Params
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              params:
                type: object
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      tags:
        - Query
definitions:
  Any:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  Status:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          properties:
            '@type':
              type: string
          additionalProperties: {}
  Params:
    type: object
  QueryGetAmountResponse:
    type: object
    properties:
      amount:
        type: string
        format: uint64
  QueryGetLastProcessedResponse:
    type: object
    properties:
      transactionId:
        type: string
  QueryParamsResponse:
    type: object
    properties:
      params:
        type: object
  MsgApproveRequestResponse:
    type: object
  MsgCreateRequestResponse:
    type: object
  MsgUpdateParamsResponse:
    type: object
