// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sigmoidtest/sigmoidtest/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5768b8b123ea4301, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5768b8b123ea4301, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetAmountRequest struct {
	SenderAddress string `protobuf:"bytes,1,opt,name=senderAddress,proto3" json:"senderAddress,omitempty"`
}

func (m *QueryGetAmountRequest) Reset()         { *m = QueryGetAmountRequest{} }
func (m *QueryGetAmountRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetAmountRequest) ProtoMessage()    {}
func (*QueryGetAmountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5768b8b123ea4301, []int{2}
}
func (m *QueryGetAmountRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetAmountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetAmountRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetAmountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetAmountRequest.Merge(m, src)
}
func (m *QueryGetAmountRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetAmountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetAmountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetAmountRequest proto.InternalMessageInfo

func (m *QueryGetAmountRequest) GetSenderAddress() string {
	if m != nil {
		return m.SenderAddress
	}
	return ""
}

type QueryGetAmountResponse struct {
	Amount uint64 `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *QueryGetAmountResponse) Reset()         { *m = QueryGetAmountResponse{} }
func (m *QueryGetAmountResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetAmountResponse) ProtoMessage()    {}
func (*QueryGetAmountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5768b8b123ea4301, []int{3}
}
func (m *QueryGetAmountResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetAmountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetAmountResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetAmountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetAmountResponse.Merge(m, src)
}
func (m *QueryGetAmountResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetAmountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetAmountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetAmountResponse proto.InternalMessageInfo

func (m *QueryGetAmountResponse) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type QueryGetLastProcessedRequest struct {
}

func (m *QueryGetLastProcessedRequest) Reset()         { *m = QueryGetLastProcessedRequest{} }
func (m *QueryGetLastProcessedRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetLastProcessedRequest) ProtoMessage()    {}
func (*QueryGetLastProcessedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5768b8b123ea4301, []int{4}
}
func (m *QueryGetLastProcessedRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetLastProcessedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetLastProcessedRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetLastProcessedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetLastProcessedRequest.Merge(m, src)
}
func (m *QueryGetLastProcessedRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetLastProcessedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetLastProcessedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetLastProcessedRequest proto.InternalMessageInfo

type QueryGetLastProcessedResponse struct {
	TransactionId string `protobuf:"bytes,1,opt,name=transactionId,proto3" json:"transactionId,omitempty"`
}

func (m *QueryGetLastProcessedResponse) Reset()         { *m = QueryGetLastProcessedResponse{} }
func (m *QueryGetLastProcessedResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetLastProcessedResponse) ProtoMessage()    {}
func (*QueryGetLastProcessedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5768b8b123ea4301, []int{5}
}
func (m *QueryGetLastProcessedResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetLastProcessedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetLastProcessedResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetLastProcessedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetLastProcessedResponse.Merge(m, src)
}
func (m *QueryGetLastProcessedResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetLastProcessedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetLastProcessedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetLastProcessedResponse proto.InternalMessageInfo

func (m *QueryGetLastProcessedResponse) GetTransactionId() string {
	if m != nil {
		return m.TransactionId
	}
	return ""
}

type QueryGetFrontStakeRequestRequest struct {
	Creator    string             `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Pagination *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryGetFrontStakeRequestRequest) Reset()         { *m = QueryGetFrontStakeRequestRequest{} }
func (m *QueryGetFrontStakeRequestRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetFrontStakeRequestRequest) ProtoMessage()    {}
func (*QueryGetFrontStakeRequestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5768b8b123ea4301, []int{6}
}
func (m *QueryGetFrontStakeRequestRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetFrontStakeRequestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetFrontStakeRequestRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetFrontStakeRequestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetFrontStakeRequestRequest.Merge(m, src)
}
func (m *QueryGetFrontStakeRequestRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetFrontStakeRequestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetFrontStakeRequestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetFrontStakeRequestRequest proto.InternalMessageInfo

func (m *QueryGetFrontStakeRequestRequest) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *QueryGetFrontStakeRequestRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetFrontStakeRequestResponse struct {
	FrontStakeRequest []FrontStakeRequest `protobuf:"bytes,1,rep,name=frontStakeRequest,proto3" json:"frontStakeRequest"`
	Pagination        *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryGetFrontStakeRequestResponse) Reset()         { *m = QueryGetFrontStakeRequestResponse{} }
func (m *QueryGetFrontStakeRequestResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetFrontStakeRequestResponse) ProtoMessage()    {}
func (*QueryGetFrontStakeRequestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5768b8b123ea4301, []int{7}
}
func (m *QueryGetFrontStakeRequestResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetFrontStakeRequestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetFrontStakeRequestResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetFrontStakeRequestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetFrontStakeRequestResponse.Merge(m, src)
}
func (m *QueryGetFrontStakeRequestResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetFrontStakeRequestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetFrontStakeRequestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetFrontStakeRequestResponse proto.InternalMessageInfo

func (m *QueryGetFrontStakeRequestResponse) GetFrontStakeRequest() []FrontStakeRequest {
	if m != nil {
		return m.FrontStakeRequest
	}
	return nil
}

func (m *QueryGetFrontStakeRequestResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "sigmoidtest.sigmoidtest.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "sigmoidtest.sigmoidtest.QueryParamsResponse")
	proto.RegisterType((*QueryGetAmountRequest)(nil), "sigmoidtest.sigmoidtest.QueryGetAmountRequest")
	proto.RegisterType((*QueryGetAmountResponse)(nil), "sigmoidtest.sigmoidtest.QueryGetAmountResponse")
	proto.RegisterType((*QueryGetLastProcessedRequest)(nil), "sigmoidtest.sigmoidtest.QueryGetLastProcessedRequest")
	proto.RegisterType((*QueryGetLastProcessedResponse)(nil), "sigmoidtest.sigmoidtest.QueryGetLastProcessedResponse")
	proto.RegisterType((*QueryGetFrontStakeRequestRequest)(nil), "sigmoidtest.sigmoidtest.QueryGetFrontStakeRequestRequest")
	proto.RegisterType((*QueryGetFrontStakeRequestResponse)(nil), "sigmoidtest.sigmoidtest.QueryGetFrontStakeRequestResponse")
}

func init() {
	proto.RegisterFile("sigmoidtest/sigmoidtest/query.proto", fileDescriptor_5768b8b123ea4301)
}

var fileDescriptor_5768b8b123ea4301 = []byte{
	// 643 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x4f, 0x6b, 0x13, 0x4f,
	0x18, 0xce, 0xf4, 0xd7, 0xe6, 0x47, 0xa6, 0x14, 0xec, 0x18, 0x6b, 0x58, 0xea, 0x36, 0xae, 0x41,
	0x43, 0xac, 0xbb, 0x26, 0xd6, 0x82, 0xd5, 0x1e, 0x1a, 0xb1, 0x45, 0xf0, 0x10, 0xe3, 0x49, 0x0f,
	0x86, 0x49, 0x76, 0xba, 0x2c, 0x36, 0x3b, 0xdb, 0x9d, 0x89, 0x58, 0x4a, 0x2f, 0xe2, 0x55, 0x10,
	0xfc, 0x12, 0xe2, 0xc9, 0x9b, 0x5f, 0xa1, 0x07, 0x0f, 0xc5, 0x5e, 0x3c, 0x89, 0x24, 0x82, 0x5f,
	0x43, 0x76, 0x66, 0x36, 0x66, 0x93, 0x6c, 0x52, 0xbd, 0x84, 0xc9, 0xfb, 0xe7, 0x79, 0x9f, 0x67,
	0xe6, 0x79, 0x17, 0x5e, 0x61, 0xae, 0xd3, 0xa6, 0xae, 0xcd, 0x09, 0xe3, 0xd6, 0xe0, 0x79, 0xbf,
	0x43, 0x82, 0x03, 0xd3, 0x0f, 0x28, 0xa7, 0xe8, 0xe2, 0x40, 0xc2, 0x1c, 0x38, 0x6b, 0x8b, 0xb8,
	0xed, 0x7a, 0xd4, 0x12, 0xbf, 0xb2, 0x56, 0xcb, 0x3a, 0xd4, 0xa1, 0xe2, 0x68, 0x85, 0x27, 0x15,
	0x5d, 0x76, 0x28, 0x75, 0xf6, 0x88, 0x85, 0x7d, 0xd7, 0xc2, 0x9e, 0x47, 0x39, 0xe6, 0x2e, 0xf5,
	0x98, 0xca, 0x96, 0x5a, 0x94, 0xb5, 0x29, 0xb3, 0x9a, 0x98, 0x11, 0x39, 0xd8, 0x7a, 0x59, 0x6e,
	0x12, 0x8e, 0xcb, 0x96, 0x8f, 0x1d, 0xd7, 0x13, 0xc5, 0xaa, 0xb6, 0x90, 0x44, 0xd8, 0xc7, 0x01,
	0x6e, 0x47, 0x88, 0xe5, 0xa4, 0xaa, 0xdd, 0x80, 0x7a, 0xbc, 0xc1, 0x38, 0x7e, 0x41, 0x1a, 0x01,
	0xd9, 0xef, 0x84, 0x8a, 0x44, 0x8b, 0x91, 0x85, 0xe8, 0x71, 0x38, 0xba, 0x26, 0x70, 0xea, 0x32,
	0x67, 0x3c, 0x85, 0xe7, 0x63, 0x51, 0xe6, 0x53, 0x8f, 0x11, 0x54, 0x85, 0x69, 0x39, 0x2f, 0x07,
	0xf2, 0xa0, 0x38, 0x5f, 0x59, 0x31, 0x13, 0xae, 0xc8, 0x94, 0x8d, 0xd5, 0xcc, 0xf1, 0xf7, 0x95,
	0xd4, 0x87, 0x5f, 0x9f, 0x4a, 0xa0, 0xae, 0x3a, 0x8d, 0x4d, 0x78, 0x41, 0x40, 0xef, 0x10, 0xbe,
	0xd5, 0xa6, 0x1d, 0x8f, 0xab, 0x99, 0xa8, 0x00, 0x17, 0x18, 0xf1, 0x6c, 0x12, 0x6c, 0xd9, 0x76,
	0x40, 0x98, 0x9c, 0x91, 0xa9, 0xc7, 0x83, 0xc6, 0x4d, 0xb8, 0x34, 0xdc, 0xae, 0xc8, 0x2d, 0xc1,
	0x34, 0x16, 0x11, 0xd1, 0x38, 0x5b, 0x57, 0xff, 0x0c, 0x1d, 0x2e, 0x47, 0x1d, 0x8f, 0x30, 0xe3,
	0xb5, 0x80, 0xb6, 0x08, 0x63, 0xc4, 0x8e, 0xb4, 0x3e, 0x80, 0x97, 0x12, 0xf2, 0x0a, 0xb8, 0x00,
	0x17, 0x78, 0x80, 0x3d, 0x86, 0x5b, 0xe1, 0x83, 0x3c, 0xb4, 0x23, 0x62, 0xb1, 0xa0, 0xf1, 0x06,
	0xc0, 0x7c, 0x84, 0xb3, 0x1d, 0x5e, 0xf7, 0x93, 0xf0, 0xb6, 0xd5, 0x90, 0x48, 0x63, 0x0e, 0xfe,
	0xdf, 0x0a, 0x08, 0xe6, 0x34, 0x50, 0x20, 0xd1, 0x5f, 0xb4, 0x0d, 0xe1, 0x9f, 0x47, 0xcf, 0xcd,
	0x88, 0xeb, 0xbd, 0x6a, 0x4a, 0x87, 0x98, 0xa1, 0x43, 0x4c, 0x69, 0x4d, 0xe5, 0x10, 0xb3, 0x86,
	0x9d, 0x3e, 0xf8, 0x40, 0xa7, 0xf1, 0x05, 0xc0, 0xcb, 0x13, 0x68, 0x28, 0x49, 0xcf, 0xe1, 0xe2,
	0xee, 0x70, 0x32, 0x07, 0xf2, 0xff, 0x15, 0xe7, 0x2b, 0xa5, 0xc4, 0x37, 0x1d, 0x81, 0xab, 0xce,
	0x86, 0xcf, 0x5b, 0x1f, 0x85, 0x42, 0x3b, 0x63, 0xd4, 0x5c, 0x9b, 0xaa, 0x46, 0x92, 0x1b, 0x94,
	0x53, 0x39, 0x9d, 0x83, 0x73, 0x42, 0x0e, 0x7a, 0x0b, 0x60, 0x5a, 0xba, 0x0a, 0x5d, 0x4f, 0xa4,
	0x38, 0x6a, 0x65, 0x6d, 0xf5, 0x6c, 0xc5, 0x72, 0xb6, 0x51, 0x7c, 0x7d, 0xfa, 0xf3, 0xfd, 0x8c,
	0x81, 0xf2, 0xd1, 0xfa, 0xdc, 0x48, 0xd8, 0x38, 0xf4, 0x11, 0xc0, 0x4c, 0xdf, 0x84, 0xc8, 0x9c,
	0x3c, 0x65, 0xd8, 0xec, 0x9a, 0x75, 0xe6, 0x7a, 0x45, 0xec, 0x9e, 0x20, 0xb6, 0x8e, 0xd6, 0x92,
	0x89, 0x39, 0x84, 0x37, 0xa4, 0xe7, 0xad, 0xc3, 0xd8, 0xd2, 0x1c, 0xa1, 0xcf, 0x00, 0x9e, 0x1b,
	0xf6, 0x37, 0xba, 0x3d, 0x95, 0xc3, 0xb8, 0x7d, 0xd1, 0xd6, 0xff, 0xb6, 0x4d, 0x29, 0x58, 0x13,
	0x0a, 0x4c, 0xb4, 0x3a, 0x59, 0xc1, 0x1e, 0x66, 0xbc, 0xe1, 0xf7, 0x49, 0x7e, 0x05, 0x30, 0x3b,
	0xce, 0xca, 0xe8, 0xce, 0x54, 0x1a, 0x49, 0x5b, 0xa8, 0x6d, 0xfc, 0x4b, 0xab, 0x52, 0x71, 0x5f,
	0xa8, 0xd8, 0x44, 0x77, 0x27, 0xab, 0x18, 0xf3, 0xc1, 0xb5, 0x0e, 0xd5, 0xae, 0x1f, 0x55, 0x37,
	0x8e, 0xbb, 0x3a, 0x38, 0xe9, 0xea, 0xe0, 0x47, 0x57, 0x07, 0xef, 0x7a, 0x7a, 0xea, 0xa4, 0xa7,
	0xa7, 0xbe, 0xf5, 0xf4, 0xd4, 0xb3, 0x7c, 0x0c, 0xf5, 0x55, 0x0c, 0x97, 0x1f, 0xf8, 0x84, 0x35,
	0xd3, 0xe2, 0xbb, 0x7d, 0xeb, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe0, 0xf6, 0xf7, 0x87, 0xc3,
	0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of GetAmount items.
	GetAmount(ctx context.Context, in *QueryGetAmountRequest, opts ...grpc.CallOption) (*QueryGetAmountResponse, error)
	// Queries a list of GetLastProcessed items.
	GetLastProcessed(ctx context.Context, in *QueryGetLastProcessedRequest, opts ...grpc.CallOption) (*QueryGetLastProcessedResponse, error)
	// Queries a list of GetFrontStakeRequest items.
	GetFrontStakeRequest(ctx context.Context, in *QueryGetFrontStakeRequestRequest, opts ...grpc.CallOption) (*QueryGetFrontStakeRequestResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/sigmoidtest.sigmoidtest.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetAmount(ctx context.Context, in *QueryGetAmountRequest, opts ...grpc.CallOption) (*QueryGetAmountResponse, error) {
	out := new(QueryGetAmountResponse)
	err := c.cc.Invoke(ctx, "/sigmoidtest.sigmoidtest.Query/GetAmount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetLastProcessed(ctx context.Context, in *QueryGetLastProcessedRequest, opts ...grpc.CallOption) (*QueryGetLastProcessedResponse, error) {
	out := new(QueryGetLastProcessedResponse)
	err := c.cc.Invoke(ctx, "/sigmoidtest.sigmoidtest.Query/GetLastProcessed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetFrontStakeRequest(ctx context.Context, in *QueryGetFrontStakeRequestRequest, opts ...grpc.CallOption) (*QueryGetFrontStakeRequestResponse, error) {
	out := new(QueryGetFrontStakeRequestResponse)
	err := c.cc.Invoke(ctx, "/sigmoidtest.sigmoidtest.Query/GetFrontStakeRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of GetAmount items.
	GetAmount(context.Context, *QueryGetAmountRequest) (*QueryGetAmountResponse, error)
	// Queries a list of GetLastProcessed items.
	GetLastProcessed(context.Context, *QueryGetLastProcessedRequest) (*QueryGetLastProcessedResponse, error)
	// Queries a list of GetFrontStakeRequest items.
	GetFrontStakeRequest(context.Context, *QueryGetFrontStakeRequestRequest) (*QueryGetFrontStakeRequestResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) GetAmount(ctx context.Context, req *QueryGetAmountRequest) (*QueryGetAmountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAmount not implemented")
}
func (*UnimplementedQueryServer) GetLastProcessed(ctx context.Context, req *QueryGetLastProcessedRequest) (*QueryGetLastProcessedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLastProcessed not implemented")
}
func (*UnimplementedQueryServer) GetFrontStakeRequest(ctx context.Context, req *QueryGetFrontStakeRequestRequest) (*QueryGetFrontStakeRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFrontStakeRequest not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sigmoidtest.sigmoidtest.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetAmount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetAmountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetAmount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sigmoidtest.sigmoidtest.Query/GetAmount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetAmount(ctx, req.(*QueryGetAmountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetLastProcessed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetLastProcessedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetLastProcessed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sigmoidtest.sigmoidtest.Query/GetLastProcessed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetLastProcessed(ctx, req.(*QueryGetLastProcessedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetFrontStakeRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetFrontStakeRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetFrontStakeRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sigmoidtest.sigmoidtest.Query/GetFrontStakeRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetFrontStakeRequest(ctx, req.(*QueryGetFrontStakeRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sigmoidtest.sigmoidtest.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "GetAmount",
			Handler:    _Query_GetAmount_Handler,
		},
		{
			MethodName: "GetLastProcessed",
			Handler:    _Query_GetLastProcessed_Handler,
		},
		{
			MethodName: "GetFrontStakeRequest",
			Handler:    _Query_GetFrontStakeRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sigmoidtest/sigmoidtest/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetAmountRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetAmountRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetAmountRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SenderAddress) > 0 {
		i -= len(m.SenderAddress)
		copy(dAtA[i:], m.SenderAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.SenderAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetAmountResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetAmountResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetAmountResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Amount != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetLastProcessedRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetLastProcessedRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetLastProcessedRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryGetLastProcessedResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetLastProcessedResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetLastProcessedResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TransactionId) > 0 {
		i -= len(m.TransactionId)
		copy(dAtA[i:], m.TransactionId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.TransactionId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetFrontStakeRequestRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetFrontStakeRequestRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetFrontStakeRequestRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetFrontStakeRequestResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetFrontStakeRequestResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetFrontStakeRequestResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.FrontStakeRequest) > 0 {
		for iNdEx := len(m.FrontStakeRequest) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.FrontStakeRequest[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetAmountRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SenderAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetAmountResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Amount != 0 {
		n += 1 + sovQuery(uint64(m.Amount))
	}
	return n
}

func (m *QueryGetLastProcessedRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryGetLastProcessedResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TransactionId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetFrontStakeRequestRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetFrontStakeRequestResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.FrontStakeRequest) > 0 {
		for _, e := range m.FrontStakeRequest {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetAmountRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetAmountRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetAmountRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SenderAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SenderAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetAmountResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetAmountResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetAmountResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetLastProcessedRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetLastProcessedRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetLastProcessedRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetLastProcessedResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetLastProcessedResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetLastProcessedResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransactionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TransactionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetFrontStakeRequestRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetFrontStakeRequestRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetFrontStakeRequestRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetFrontStakeRequestResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetFrontStakeRequestResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetFrontStakeRequestResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FrontStakeRequest", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FrontStakeRequest = append(m.FrontStakeRequest, FrontStakeRequest{})
			if err := m.FrontStakeRequest[len(m.FrontStakeRequest)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
